name: Security Analysis (SAST)

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]

      - name: Run Bandit security scan
        run: |
          bandit -r app/ -f json -o bandit-report.json || true
          bandit -r app/ -f txt -o bandit-report.txt || true

      - name: Upload Bandit scan results
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: |
            bandit-report.json
            bandit-report.txt

      - name: Display security summary
        run: |
          echo "=== Security Scan Summary ==="
          bandit -r app/ --severity-level medium || true