name: Build, Push, and Deploy to ECS

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ -z "$VERSION" || "$GITHUB_REF" != refs/tags/* ]]; then
            VERSION=latest
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hello-you-api:${{ steps.vars.outputs.version }}
            ghcr.io/${{ github.repository }}/hello-you-api:latest

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.region }}
#
#      - name: Force ECS service update
#        run: |
#          aws ecs update-service \
#            --cluster ${{ secrets.ECS_CLUSTER }} \
#            --service ${{ secrets.ECS_SERVICE }} \
#            --force-new-deployment

